APP = ./tcpmerge
CC=gcc -g -O0  -DTCPMERGE_TEST=1
CFLAGS=  -static -ldl -lrt -lpthread -Wall -Wextra -L./  -lpcap_file_generator

all: $(APP)

$(APP): tcpmerge.o
	$(CC) tcpmerge.o -o $(APP) $(CFLAGS)
tcpmerge.o: tcpmerge.c	
	$(CC) tcpmerge.c -c -Wall

clean:
	rm -f *.o ; rm $(APP)
